-- NavalGO PostgreSQL schema aligned with current Spring Boot backend
-- Target: clean database (empty)
-- PostgreSQL 14+

BEGIN;

-- =========================================================
-- 1) Core tables used by current backend (JPA entities)
-- =========================================================

CREATE TABLE IF NOT EXISTS workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    speciality VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_workers_role CHECK (role IN ('ADMIN', 'WORKER'))
);

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tax_id VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    document_id VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    email VARCHAR(255),
    company_id BIGINT,
    CONSTRAINT fk_owners_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT ck_owners_type CHECK (type IN ('PERSON', 'COMPANY'))
);

CREATE TABLE IF NOT EXISTS vessels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL UNIQUE,
    model VARCHAR(255),
    engine_count INTEGER,
    length_meters DOUBLE PRECISION,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_vessels_owner FOREIGN KEY (owner_id) REFERENCES owners(id)
);

CREATE TABLE IF NOT EXISTS work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(3000),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    owner_id BIGINT NOT NULL,
    vessel_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_orders_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_work_orders_vessel FOREIGN KEY (vessel_id) REFERENCES vessels(id),
    CONSTRAINT ck_work_orders_status CHECK (status IN ('NEW', 'IN_PROGRESS', 'DONE', 'CANCELLED')),
    CONSTRAINT ck_work_orders_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT'))
);

CREATE TABLE IF NOT EXISTS work_order_workers (
    work_order_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,
    PRIMARY KEY (work_order_id, worker_id),
    CONSTRAINT fk_wow_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wow_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS engine_hour_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    engine_label VARCHAR(255) NOT NULL,
    hours INTEGER NOT NULL,
    CONSTRAINT fk_engine_logs_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    CONSTRAINT fk_wo_attachments_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    clock_in TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    clock_out TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_time_entries_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT fk_leave_requests_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT ck_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_leave_dates CHECK (end_date >= start_date)
);

-- =========================================================
-- 2) ACL tables to keep old DB capabilities (roles/permisos)
--    Not required by current backend login, but preserved.
-- =========================================================

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS rol_permisos (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT fk_rol_permisos_rol FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id) REFERENCES permisos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usuario_roles (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_roles_worker FOREIGN KEY (usuario_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- =========================================================
-- 3) Indexes for performance
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_workers_email ON workers(email);
CREATE INDEX IF NOT EXISTS idx_vessels_owner_id ON vessels(owner_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_owner_id ON work_orders(owner_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_vessel_id ON work_orders(vessel_id);
CREATE INDEX IF NOT EXISTS idx_wow_worker_id ON work_order_workers(worker_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_worker_id ON time_entries(worker_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_worker_id ON leave_requests(worker_id);

-- =========================================================
-- 4) Seed ACL and app baseline data
--    Workers seed is optional; if omitted, DataInitializer will create users.
-- =========================================================

INSERT INTO roles (nombre_rol, descripcion)
SELECT 'ADMIN', 'Acceso total'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE nombre_rol = 'ADMIN');

INSERT INTO roles (nombre_rol, descripcion)
SELECT 'MECANICO_JEFE', 'Supervisa partes'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE nombre_rol = 'MECANICO_JEFE');

INSERT INTO roles (nombre_rol, descripcion)
SELECT 'MECANICO', 'Realiza trabajos'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE nombre_rol = 'MECANICO');

INSERT INTO permisos (nombre_permiso, descripcion)
SELECT 'GESTIONAR_USUARIOS', 'Gestion de usuarios'
WHERE NOT EXISTS (SELECT 1 FROM permisos WHERE nombre_permiso = 'GESTIONAR_USUARIOS');

INSERT INTO permisos (nombre_permiso, descripcion)
SELECT 'EDITAR_PARTE_AJENO', 'Edicion de partes ajenos'
WHERE NOT EXISTS (SELECT 1 FROM permisos WHERE nombre_permiso = 'EDITAR_PARTE_AJENO');

INSERT INTO permisos (nombre_permiso, descripcion)
SELECT 'EDITAR_PARTE_PROPIO', 'Edicion de partes propios'
WHERE NOT EXISTS (SELECT 1 FROM permisos WHERE nombre_permiso = 'EDITAR_PARTE_PROPIO');

INSERT INTO permisos (nombre_permiso, descripcion)
SELECT 'APROBAR_VACACIONES', 'Aprobacion de ausencias'
WHERE NOT EXISTS (SELECT 1 FROM permisos WHERE nombre_permiso = 'APROBAR_VACACIONES');

-- =========================================================
-- 5) Legacy compatibility views (read-only)
--    Keep old naming model available for queries/reporting.
-- =========================================================

CREATE OR REPLACE VIEW usuarios AS
SELECT
    w.id,
    w.full_name AS nombre,
    w.email,
    w.password_hash AS password,
    w.speciality AS especialidad,
    CASE WHEN w.active THEN 'ACTIVO' ELSE 'INACTIVO' END AS estado,
    NULL::timestamp without time zone AS fecha_creacion
FROM workers w;

CREATE OR REPLACE VIEW clientes AS
SELECT
    o.id,
    CASE WHEN o.type = 'COMPANY' THEN 'EMPRESA' ELSE 'PARTICULAR' END AS tipo_cliente,
    o.document_id AS documento_identidad,
    o.display_name AS nombre_principal,
    NULL::varchar(100) AS persona_contacto,
    o.phone AS telefono,
    o.email,
    NULL::timestamp without time zone AS fecha_creacion
FROM owners o;

CREATE OR REPLACE VIEW barcos AS
SELECT
    v.id,
    v.owner_id AS cliente_id,
    v.name AS nombre,
    v.registration_number AS matricula,
    v.length_meters::numeric(5,2) AS eslora,
    v.model AS tipo,
    NULL::timestamp without time zone AS fecha_registro
FROM vessels v;

CREATE OR REPLACE VIEW partes_trabajo AS
SELECT
    wo.id,
    wo.vessel_id AS barco_id,
    wo.title AS titulo,
    wo.description AS descripcion,
    (
      SELECT COUNT(*)::integer
      FROM engine_hour_logs e
      WHERE e.work_order_id = wo.id
    ) AS numero_motores,
    CASE wo.status
      WHEN 'NEW' THEN 'PENDIENTE'
      WHEN 'IN_PROGRESS' THEN 'EN_CURSO'
      WHEN 'DONE' THEN 'FINALIZADO'
      WHEN 'CANCELLED' THEN 'CANCELADO'
      ELSE wo.status
    END AS estado,
    wo.priority AS prioridad,
    wo.created_at AS fecha_creacion,
    NULL::timestamp without time zone AS fecha_finalizacion
FROM work_orders wo;

CREATE OR REPLACE VIEW parte_asignaciones AS
SELECT
    wow.work_order_id AS parte_id,
    wow.worker_id AS usuario_id
FROM work_order_workers wow;

CREATE OR REPLACE VIEW motores_parte AS
SELECT
    e.id,
    e.work_order_id AS parte_id,
    e.engine_label AS identificador_motor,
    e.hours::numeric(10,2) AS horas_uso
FROM engine_hour_logs e;

CREATE OR REPLACE VIEW adjuntos_parte AS
SELECT
    a.id,
    a.work_order_id AS parte_id,
    a.file_url AS clave_objeto,
    a.file_type AS tipo_archivo,
    NULL::varchar(255) AS nombre_original,
    NULL::timestamp without time zone AS fecha_subida
FROM work_order_attachments a;

CREATE OR REPLACE VIEW ausencias AS
SELECT
    l.id,
    l.worker_id AS usuario_id,
    l.start_date AS fecha_inicio,
    l.end_date AS fecha_fin,
    CASE l.status
      WHEN 'PENDING' THEN 'PENDIENTE'
      WHEN 'APPROVED' THEN 'APROBADA'
      WHEN 'REJECTED' THEN 'RECHAZADA'
      ELSE l.status
    END AS estado,
    l.reason AS descripcion,
    NULL::timestamp without time zone AS fecha_solicitud,
    'GENERAL'::varchar(50) AS tipo_ausencia
FROM leave_requests l;

CREATE OR REPLACE VIEW fichajes AS
SELECT
    t.id,
    t.worker_id AS usuario_id,
    'JORNADA'::varchar(20) AS tipo,
    t.clock_in AS fecha_hora,
    NULL::numeric(9,6) AS latitud,
    NULL::numeric(9,6) AS longitud,
    NULL::text AS notas
FROM time_entries t;

COMMIT;
