-- NavalGO — esquema PostgreSQL limpio para el backend Spring Boot actual
-- Compatible con: instalación nueva Y base de datos existente (migraciones IF NOT EXISTS)
-- PostgreSQL 14+

BEGIN;

-- =========================================================
-- TABLAS PRINCIPALES (entidades JPA del backend)
-- =========================================================

CREATE TABLE IF NOT EXISTS workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    speciality VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE,
    contract_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_workers_role CHECK (role IN ('ADMIN', 'WORKER'))
);

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tax_id VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    document_id VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    email VARCHAR(255),
    company_id BIGINT,
    CONSTRAINT fk_owners_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT ck_owners_type CHECK (type IN ('PERSON', 'COMPANY'))
);

CREATE TABLE IF NOT EXISTS vessels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL UNIQUE,
    model VARCHAR(255),
    engine_count INTEGER,
    engine_labels VARCHAR(1000),
    length_meters DOUBLE PRECISION,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_vessels_owner FOREIGN KEY (owner_id) REFERENCES owners(id)
);

CREATE TABLE IF NOT EXISTS work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(3000),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    owner_id BIGINT NOT NULL,
    vessel_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_orders_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_work_orders_vessel FOREIGN KEY (vessel_id) REFERENCES vessels(id),
    CONSTRAINT ck_work_orders_status CHECK (status IN ('NEW', 'IN_PROGRESS', 'DONE', 'CANCELLED')),
    CONSTRAINT ck_work_orders_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT'))
);

CREATE TABLE IF NOT EXISTS work_order_workers (
    work_order_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,
    PRIMARY KEY (work_order_id, worker_id),
    CONSTRAINT fk_wow_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wow_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS engine_hour_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    engine_label VARCHAR(255) NOT NULL,
    hours INTEGER NOT NULL,
    CONSTRAINT fk_engine_logs_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    file_url VARCHAR(2000) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    captured_at TIMESTAMP WITHOUT TIME ZONE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    watermarked BOOLEAN NOT NULL DEFAULT FALSE,
    audio_removed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_wo_attachments_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    clock_in TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    clock_out TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_time_entries_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT fk_leave_requests_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT ck_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_leave_dates CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    type VARCHAR(20) NOT NULL,
    action_route VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT ck_notification_type CHECK (type IN ('INFO', 'WARNING', 'SUCCESS'))
);

-- =========================================================
-- ÍNDICES DE RENDIMIENTO
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_workers_email ON workers(email);
CREATE INDEX IF NOT EXISTS idx_vessels_owner_id ON vessels(owner_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_owner_id ON work_orders(owner_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_vessel_id ON work_orders(vessel_id);
CREATE INDEX IF NOT EXISTS idx_wow_worker_id ON work_order_workers(worker_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_worker_id ON time_entries(worker_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_worker_id ON leave_requests(worker_id);
CREATE INDEX IF NOT EXISTS idx_notifications_worker_id ON notifications(worker_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(worker_id, is_read);

-- =========================================================
-- MIGRACIONES (para bases de datos existentes)
-- Añade columnas nuevas si no existen — no afecta instalaciones nuevas
-- =========================================================

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE;

-- v3: profile photo, work order digital signature
ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS photo_url VARCHAR(1000);

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signature_url VARCHAR(2000);

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS contract_start_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS original_file_name VARCHAR(255);

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS captured_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS watermarked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS audio_removed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_order_attachments
    ALTER COLUMN file_url TYPE VARCHAR(2000);

ALTER TABLE vessels
    ADD COLUMN IF NOT EXISTS engine_labels VARCHAR(1000);

COMMIT;
