-- NavalGO — esquema PostgreSQL limpio para el backend Spring Boot actual
-- Compatible con: instalación nueva Y base de datos existente (migraciones IF NOT EXISTS)
-- PostgreSQL 14+

BEGIN;

-- =========================================================
-- TABLAS PRINCIPALES (entidades JPA del backend)
-- =========================================================

CREATE TABLE IF NOT EXISTS workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    speciality VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE,
    contract_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_workers_role CHECK (role IN ('ADMIN', 'WORKER'))
);

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tax_id VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    document_id VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    email VARCHAR(255),
    company_id BIGINT,
    CONSTRAINT fk_owners_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT ck_owners_type CHECK (type IN ('PERSON', 'COMPANY'))
);

CREATE TABLE IF NOT EXISTS vessels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL UNIQUE,
    model VARCHAR(255),
    engine_count INTEGER,
    engine_labels VARCHAR(1000),
    engine_serial_number VARCHAR(255),
    length_meters DOUBLE PRECISION,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_vessels_owner FOREIGN KEY (owner_id) REFERENCES owners(id)
);

CREATE TABLE IF NOT EXISTS work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(3000),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    owner_id BIGINT NOT NULL,
    vessel_id BIGINT,
    labor_hours NUMERIC(8,2),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    signature_url VARCHAR(2000),
    signed_at TIMESTAMP WITHOUT TIME ZONE,
    signed_by_worker_id BIGINT,
    CONSTRAINT fk_work_orders_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_work_orders_vessel FOREIGN KEY (vessel_id) REFERENCES vessels(id),
    CONSTRAINT fk_work_orders_signed_by_worker FOREIGN KEY (signed_by_worker_id) REFERENCES workers(id),
    CONSTRAINT ck_work_orders_status CHECK (status IN ('NEW', 'IN_PROGRESS', 'DONE', 'CANCELLED')),
    CONSTRAINT ck_work_orders_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT'))
);

CREATE TABLE IF NOT EXISTS work_order_workers (
    work_order_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,
    PRIMARY KEY (work_order_id, worker_id),
    CONSTRAINT fk_wow_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_wow_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS engine_hour_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    engine_label VARCHAR(255) NOT NULL,
    hours INTEGER NOT NULL,
    CONSTRAINT fk_engine_logs_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    file_url VARCHAR(2000) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    captured_at TIMESTAMP WITHOUT TIME ZONE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    watermarked BOOLEAN NOT NULL DEFAULT FALSE,
    audio_removed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_wo_attachments_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS material_checklist_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS material_checklist_template_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    article_name VARCHAR(255) NOT NULL,
    reference_code VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_mcti_template FOREIGN KEY (template_id) REFERENCES material_checklist_templates(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_order_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL UNIQUE,
    source_template_id BIGINT,
    source_template_name VARCHAR(255) NOT NULL,
    assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_woc_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_order_checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id BIGINT NOT NULL,
    source_template_item_id BIGINT,
    article_name VARCHAR(255) NOT NULL,
    reference_code VARCHAR(255) NOT NULL,
    checked BOOLEAN NOT NULL DEFAULT FALSE,
    checked_at TIMESTAMP WITHOUT TIME ZONE,
    checked_by_worker_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_woci_checklist FOREIGN KEY (checklist_id) REFERENCES work_order_checklists(id) ON DELETE CASCADE,
    CONSTRAINT fk_woci_checked_by_worker FOREIGN KEY (checked_by_worker_id) REFERENCES workers(id)
);

CREATE TABLE IF NOT EXISTS material_revision_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    checklist_item_snapshot_id BIGINT,
    source_template_id BIGINT,
    source_template_item_id BIGINT,
    article_name VARCHAR(255) NOT NULL,
    reference_code VARCHAR(255) NOT NULL,
    observations VARCHAR(3000) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    requested_by_worker_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by_worker_id BIGINT,
    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    resolution_note VARCHAR(1000),
    CONSTRAINT fk_mrr_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_mrr_checklist_item FOREIGN KEY (checklist_item_snapshot_id) REFERENCES work_order_checklist_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_mrr_requested_by_worker FOREIGN KEY (requested_by_worker_id) REFERENCES workers(id),
    CONSTRAINT fk_mrr_reviewed_by_worker FOREIGN KEY (reviewed_by_worker_id) REFERENCES workers(id),
    CONSTRAINT ck_mrr_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    clock_in TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    clock_out TIMESTAMP WITHOUT TIME ZONE,
    work_site VARCHAR(20) NOT NULL DEFAULT 'WORKSHOP',
    CONSTRAINT fk_time_entries_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT fk_leave_requests_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT ck_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_leave_dates CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    token_prefix VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    rotated_at TIMESTAMP WITHOUT TIME ZONE,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    issued_ip VARCHAR(128),
    user_agent VARCHAR(512),
    CONSTRAINT fk_refresh_tokens_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    type VARCHAR(20) NOT NULL,
    action_route VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT ck_notification_type CHECK (type IN ('INFO', 'WARNING', 'SUCCESS'))
);

-- =========================================================
-- ÍNDICES DE RENDIMIENTO
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_workers_email ON workers(email);
CREATE INDEX IF NOT EXISTS idx_vessels_owner_id ON vessels(owner_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_owner_id ON work_orders(owner_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_vessel_id ON work_orders(vessel_id);
CREATE INDEX IF NOT EXISTS idx_wow_worker_id ON work_order_workers(worker_id);
CREATE INDEX IF NOT EXISTS idx_material_checklist_templates_updated_at ON material_checklist_templates(updated_at);
CREATE INDEX IF NOT EXISTS idx_mcti_template_id ON material_checklist_template_items(template_id);
CREATE INDEX IF NOT EXISTS idx_woc_work_order_id ON work_order_checklists(work_order_id);
CREATE INDEX IF NOT EXISTS idx_woci_checklist_id ON work_order_checklist_items(checklist_id);
CREATE INDEX IF NOT EXISTS idx_woci_checked_by_worker_id ON work_order_checklist_items(checked_by_worker_id);
CREATE INDEX IF NOT EXISTS idx_mrr_work_order_id ON material_revision_requests(work_order_id);
CREATE INDEX IF NOT EXISTS idx_mrr_source_template_id ON material_revision_requests(source_template_id);
CREATE INDEX IF NOT EXISTS idx_mrr_status ON material_revision_requests(status);
CREATE INDEX IF NOT EXISTS idx_time_entries_worker_id ON time_entries(worker_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_worker_id ON leave_requests(worker_id);
CREATE INDEX IF NOT EXISTS idx_notifications_worker_id ON notifications(worker_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(worker_id, is_read);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_worker ON refresh_tokens(worker_id);

-- =========================================================
-- MIGRACIONES (para bases de datos existentes)
-- Añade columnas nuevas si no existen — no afecta instalaciones nuevas
-- =========================================================

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE;

-- v3: profile photo, work order digital signature
ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS photo_url VARCHAR(1000);

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signature_url VARCHAR(2000);

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signed_by_worker_id BIGINT;

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS labor_hours NUMERIC(8,2);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_work_orders_signed_by_worker'
    ) THEN
        ALTER TABLE work_orders
            ADD CONSTRAINT fk_work_orders_signed_by_worker
            FOREIGN KEY (signed_by_worker_id) REFERENCES workers(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_work_orders_signed_by_worker_id ON work_orders(signed_by_worker_id);

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS contract_start_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS original_file_name VARCHAR(255);

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS captured_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS watermarked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS audio_removed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_order_attachments
    ALTER COLUMN file_url TYPE VARCHAR(2000);

ALTER TABLE time_entries
    ADD COLUMN IF NOT EXISTS work_site VARCHAR(20) NOT NULL DEFAULT 'WORKSHOP';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_time_entries_work_site'
    ) THEN
        ALTER TABLE time_entries DROP CONSTRAINT ck_time_entries_work_site;
    END IF;
END $$;

ALTER TABLE time_entries
    ADD CONSTRAINT ck_time_entries_work_site CHECK (work_site IN ('WORKSHOP', 'TRAVEL'));

ALTER TABLE vessels
    ADD COLUMN IF NOT EXISTS engine_labels VARCHAR(1000);

ALTER TABLE vessels
    ADD COLUMN IF NOT EXISTS engine_serial_number VARCHAR(255);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_leave_status'
    ) THEN
        ALTER TABLE leave_requests DROP CONSTRAINT ck_leave_status;
    END IF;
END $$;

ALTER TABLE leave_requests
    ADD CONSTRAINT ck_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'));

COMMIT;
