-- NavalGO - migracion idempotente para bases PostgreSQL existentes.
-- Ejecuta este fichero en produccion antes de arrancar una version nueva del backend.
-- Para instalaciones nuevas sigue usando `navalgo_backend_postgres.sql`.

BEGIN;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS can_edit_work_orders BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS photo_url VARCHAR(1000);

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS contract_start_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signature_url VARCHAR(2000);

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS signed_by_worker_id BIGINT;

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS labor_hours NUMERIC(8,2);

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS close_due_date DATE;

ALTER TABLE work_orders
    ADD COLUMN IF NOT EXISTS last_close_reminder_sent_at TIMESTAMP WITHOUT TIME ZONE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_work_orders_signed_by_worker'
    ) THEN
        ALTER TABLE work_orders
            ADD CONSTRAINT fk_work_orders_signed_by_worker
            FOREIGN KEY (signed_by_worker_id) REFERENCES workers(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_work_orders_signed_by_worker_id ON work_orders(signed_by_worker_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_close_due_date ON work_orders(close_due_date);

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS original_file_name VARCHAR(255);

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS captured_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS watermarked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_order_attachments
    ADD COLUMN IF NOT EXISTS audio_removed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_order_attachments
    ALTER COLUMN file_url TYPE VARCHAR(2000);

ALTER TABLE time_entries
    ADD COLUMN IF NOT EXISTS work_site VARCHAR(20) NOT NULL DEFAULT 'WORKSHOP';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_time_entries_work_site'
    ) THEN
        ALTER TABLE time_entries DROP CONSTRAINT ck_time_entries_work_site;
    END IF;
END $$;

ALTER TABLE time_entries
    ADD CONSTRAINT ck_time_entries_work_site CHECK (work_site IN ('WORKSHOP', 'TRAVEL'));

ALTER TABLE vessels
    ADD COLUMN IF NOT EXISTS engine_labels VARCHAR(1000);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'vessels'
          AND column_name = 'engine_serial_number'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'vessels'
          AND column_name = 'engine_serial_numbers'
    ) THEN
        ALTER TABLE vessels RENAME COLUMN engine_serial_number TO engine_serial_numbers;
    END IF;
END $$;

ALTER TABLE vessels
    ADD COLUMN IF NOT EXISTS engine_serial_numbers VARCHAR(1000);

ALTER TABLE vessels
    ALTER COLUMN engine_serial_numbers TYPE VARCHAR(1000);

ALTER TABLE vessels
    DROP COLUMN IF EXISTS engine_serial_number;

CREATE TABLE IF NOT EXISTS time_adjustment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    time_entry_id BIGINT,
    work_date DATE NOT NULL,
    requested_clock_in TIMESTAMP WITHOUT TIME ZONE,
    requested_clock_out TIMESTAMP WITHOUT TIME ZONE,
    work_site VARCHAR(20) NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    admin_comment VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    reviewed_by_worker_id BIGINT,
    CONSTRAINT fk_tar_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT fk_tar_time_entry FOREIGN KEY (time_entry_id) REFERENCES time_entries(id) ON DELETE SET NULL,
    CONSTRAINT fk_tar_reviewed_by_worker FOREIGN KEY (reviewed_by_worker_id) REFERENCES workers(id),
    CONSTRAINT ck_tar_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_tar_work_site CHECK (work_site IN ('WORKSHOP', 'TRAVEL'))
);

CREATE INDEX IF NOT EXISTS idx_time_adjustment_requests_worker_id ON time_adjustment_requests(worker_id);
CREATE INDEX IF NOT EXISTS idx_time_adjustment_requests_status ON time_adjustment_requests(status);
CREATE INDEX IF NOT EXISTS idx_time_adjustment_requests_time_entry_id ON time_adjustment_requests(time_entry_id);

CREATE TABLE IF NOT EXISTS worker_push_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    token VARCHAR(4096) NOT NULL UNIQUE,
    platform VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_worker_push_tokens_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_worker_push_tokens_worker_active ON worker_push_tokens(worker_id, active);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_leave_status'
    ) THEN
        ALTER TABLE leave_requests DROP CONSTRAINT ck_leave_status;
    END IF;
END $$;

ALTER TABLE leave_requests
    ADD CONSTRAINT ck_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'));

COMMIT;