// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcgQPb2xVH5qEucH_yetrZqnhA2xAWrM',
    appId: '1:201883315763:web:a87e3264bca378024dbd46',
    messagingSenderId: '201883315763',
    projectId: 'naval-go',
    authDomain: 'naval-go.firebaseapp.com',
    storageBucket: 'naval-go.firebasestorage.app',
    measurementId: 'G-V45H99BJT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAccLlDvNplZOtO6K7Umx6fXtpkz0Vg0TA',
    appId: '1:201883315763:android:cc1fb6527634ce724dbd46',
    messagingSenderId: '201883315763',
    projectId: 'naval-go',
    storageBucket: 'naval-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYuAIohRCXrJ0PWf1rus9uXSaEcyt1ZZg',
    appId: '1:201883315763:ios:ea2ca86ad79586234dbd46',
    messagingSenderId: '201883315763',
    projectId: 'naval-go',
    storageBucket: 'naval-go.firebasestorage.app',
    iosBundleId: 'com.example.navalgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYuAIohRCXrJ0PWf1rus9uXSaEcyt1ZZg',
    appId: '1:201883315763:ios:ea2ca86ad79586234dbd46',
    messagingSenderId: '201883315763',
    projectId: 'naval-go',
    storageBucket: 'naval-go.firebasestorage.app',
    iosBundleId: 'com.example.navalgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbcgQPb2xVH5qEucH_yetrZqnhA2xAWrM',
    appId: '1:201883315763:web:37a312443f8edf854dbd46',
    messagingSenderId: '201883315763',
    projectId: 'naval-go',
    authDomain: 'naval-go.firebaseapp.com',
    storageBucket: 'naval-go.firebasestorage.app',
    measurementId: 'G-WVJ3NRD9WG',
  );
}
