BEGIN;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS owner_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_workers_role'
    ) THEN
        ALTER TABLE workers DROP CONSTRAINT ck_workers_role;
    END IF;
END $$;

ALTER TABLE workers
    ADD CONSTRAINT ck_workers_role CHECK (role IN ('ADMIN', 'COMERCIAL', 'WORKER', 'CLIENT'));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_workers_owner'
    ) THEN
        ALTER TABLE workers
            ADD CONSTRAINT fk_workers_owner FOREIGN KEY (owner_id) REFERENCES owners(id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_workers_owner_id ON workers(owner_id) WHERE owner_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_workers_owner_id ON workers(owner_id);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_email_verification_tokens_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_email_verification_tokens_worker_id ON email_verification_tokens(worker_id);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_password_reset_tokens_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_worker_id ON password_reset_tokens(worker_id);

COMMIT;
