BEGIN;

CREATE TABLE IF NOT EXISTS whatsapp_clock_in_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    reminder_date DATE NOT NULL,
    phone_number VARCHAR(32) NOT NULL,
    state VARCHAR(32) NOT NULL,
    time_entry_id BIGINT,
    requested_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    clock_in_recorded_at TIMESTAMP WITHOUT TIME ZONE,
    location_requested_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    last_inbound_at TIMESTAMP WITHOUT TIME ZONE,
    raw_clock_in_text VARCHAR(32),
    CONSTRAINT fk_whatsapp_clock_in_conversations_worker
        FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT fk_whatsapp_clock_in_conversations_time_entry
        FOREIGN KEY (time_entry_id) REFERENCES time_entries(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_clock_in_conversations_worker_id
    ON whatsapp_clock_in_conversations(worker_id);

CREATE INDEX IF NOT EXISTS idx_whatsapp_clock_in_conversations_phone_state
    ON whatsapp_clock_in_conversations(phone_number, state);

COMMIT;
