BEGIN;

CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    vessel_id BIGINT NOT NULL,
    created_by_worker_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(3000),
    amount NUMERIC(12,2),
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    pdf_url VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    client_observations VARCHAR(2000),
    sent_at TIMESTAMP WITHOUT TIME ZONE,
    client_decided_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_budgets_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_budgets_vessel FOREIGN KEY (vessel_id) REFERENCES vessels(id),
    CONSTRAINT fk_budgets_created_by_worker FOREIGN KEY (created_by_worker_id) REFERENCES workers(id),
    CONSTRAINT ck_budgets_status CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_budgets_owner_id ON budgets(owner_id);
CREATE INDEX IF NOT EXISTS idx_budgets_vessel_id ON budgets(vessel_id);
CREATE INDEX IF NOT EXISTS idx_budgets_status ON budgets(status);
CREATE INDEX IF NOT EXISTS idx_budgets_created_at ON budgets(created_at);

COMMIT;
